export type MovementType =
 "OPENING_STOCK"|"PURCHASE"|"ADJUSTMENT_IN"|"TRANSFER_IN"|"RETURN_IN"|
 "CONSUMPTION"|"SALES_ADJUSTMENT"|"WASTAGE"|"EXPIRED"|"DAMAGED"|"TRANSFER_OUT"|"ADJUSTMENT_OUT";
export type BatchStatus="ACTIVE"|"EXPIRING_SOON"|"EXPIRED"|"DEPLETED";
