"use client";
import {useEffect,useState} from "react"; import {createClient} from "@/lib/supabase/client";
export default function ReceiveStockForm(){
 const [products,setProducts]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{const db=createClient(); Promise.all([db.from("products").select("id,name,unit").eq("is_active",true).order("name"),db.from("suppliers").select("id,supplier_name").eq("is_active",true).order("supplier_name")]).then(([p,s])=>{setProducts(p.data||[]);setSuppliers(s.data||[])})},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Saving...");const f=new FormData(e.currentTarget); const db=createClient();
 const {error}=await db.rpc("receive_inventory",{p_product_id:f.get("product_id"),p_supplier_id:f.get("supplier_id")||null,p_quantity:Number(f.get("quantity")),p_purchase_cost:Number(f.get("purchase_cost")),p_batch_number:String(f.get("batch_number")),p_expiry_date:String(f.get("expiry_date")),p_manufacturing_date:f.get("manufacturing_date")||null,p_invoice_number:f.get("invoice_number")||null,p_received_date:String(f.get("received_date"))});
 setMessage(error?error.message:"Stock received successfully."); if(!error)e.currentTarget.reset();}
 return <form className="form card" onSubmit={submit}><div className="field"><label>Supplier</label><select name="supplier_id"><option value="">Select supplier</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.supplier_name}</option>)}</select></div><div className="field"><label>Product</label><select required name="product_id"><option value="">Select product</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} ({p.unit})</option>)}</select></div><div className="field"><label>Quantity</label><input required min="0.001" step="0.001" name="quantity" type="number"/></div><div className="field"><label>Purchase Cost / Unit</label><input required min="0" step="0.01" name="purchase_cost" type="number"/></div><div className="field"><label>Batch Number</label><input required name="batch_number"/></div><div className="field"><label>Manufacturing Date (optional)</label><input name="manufacturing_date" type="date"/></div><div className="field"><label>Expiry Date</label><input required name="expiry_date" type="date"/></div><div className="field"><label>Invoice Number (optional)</label><input name="invoice_number"/></div><div className="field"><label>Received Date</label><input required defaultValue={new Date().toISOString().slice(0,10)} name="received_date" type="date"/></div><button className="btn">Receive Stock</button><div className="muted">{message}</div></form>
}
